export const traducciones = {
  // Colores
  azul: "blue",
  rojo: "red",
  verde: "green",
  negro: "black",
  blanco: "white",
  rosa: "pink",
  amarillo: "yellow",
  violeta: "purple",

  // Frutas
  naranja: "orange",
  limon: "lemon",
  limón: "lemon",
  lima: "lime",
  anana: "pineapple",
  ananá: "pineapple",
  piña: "pineapple",
  frutilla: "strawberry",
  frambuesa: "raspberry",
  banana: "banana",
  cereza: "cherry",
  durazno: "peach",
  manzana: "apple",
  melon: "melon",
  melón: "melon",
  coco: "coconut",

  // Bebidas
  vodka: "vodka",
  gin: "gin",
  ron: "rum",
  whisky: "whiskey",
  tequila: "tequila",
  brandy: "brandy",
  vino: "wine",
  champagne: "champagne",
  cerveza: "beer",

  // Ingredientes
  menta: "mint",
  hielo: "ice",
  azucar: "sugar",
  azúcar: "sugar",
  miel: "honey",
  cafe: "coffee",
  café: "coffee",
  chocolate: "chocolate",
  crema: "cream",
  leche: "milk",

  // Cócteles
  destornillador: "Screwdriver",
  "laguna azul": "Blue Lagoon",
  "sexo en la playa": "Sex on the Beach",
  "cuba libre": "Cuba Libre",
  "ron con coca": "Cuba Libre",
  "piña colada": "Pina Colada",
  caipiriña: "Caipirinha",
  caipirinha: "Caipirinha",
  "tequila sunrise": "Tequila Sunrise",
  "bloody mary": "Bloody Mary",
  "gin tonic": "Gin Tonic",
  mojito: "Mojito",
  margarita: "Margarita",
  martini: "Martini",
  negroni: "Negroni",
  daiquiri: "Daiquiri",
  cosmopolitan: "Cosmopolitan",
};
